project_name: "validation"
station_name: "DAV"
series: "c"
time_resolution: "1d"
version: 8
Tice_cover: 0.0
objective_function: "NSE"
integrator: "RK4"
run_mode: "PSO"
prc: 1.0
mineff_index: -999.0

paths:
  input_data: "examples/validation/Switzerland/DAV_2327_cc.csv"
  validation_data: "examples/validation/Switzerland/DAV_2327_cv.csv"
  output_dir: "examples/validation/Switzerland/output_8"

optimization:
  n_runs: 3000
  n_particles: 100
  c1: 2.0
  c2: 2.0
  wmax: 0.9
  wmin: 0.4

parameter_bounds:
  min: [-5.0, -5.0, -5.0, -1.0, 0.0, 0.0, 0.0, -1.0]
  max: [15.0, 1.5, 5.0, 1.0, 20.0, 10.0, 1.0, 5.0]
