Tice_cover: 0.0
forward_options:
  enable_prediction_intervals: true
  mcmc_chain_path: examples/forward_prediction_intervals/MCMC_chain_Alpha_historical_1d.csv
  n_samples: 500
  random_seed: 42
  residual_sigma: 0.8217528451409142
integrator: RK4
objective_function: NSE
parameter_bounds:
  max:
  - 5.0
  - 1.0
  - 1.0
  - 1.0
  - 5.0
  - 5.0
  - 1.0
  - 1.0
  min:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
parameters_forward:
- 0.36228690142163905
- 0.044849652583495624
- 0.057504755067705075
- 0.410017442097312
- 2.032503152653831
- 1.2204373183015116
- 0.50991029706049
- 0.19169513077083503
paths:
  input_data: examples/forward_prediction_intervals/future_data.csv
  output_dir: examples/forward_prediction_intervals
prc: 1.0
project_name: projection
run_mode: FORWARD
series: future
station_name: Alpha
time_resolution: 1d
uncertainty_options:
  noise_model: iid
version: 8
