Tice_cover: 0.0
forward_options:
  enable_prediction_intervals: true
  mcmc_chain_path: examples/forward_prediction_intervals/MCMC_chain_Alpha_historical_1d.csv
  n_samples: 500
  random_seed: 42
  residual_sigma: 0.8568699472786329
integrator: RK4
objective_function: NSE
parameter_bounds:
  max:
  - 5.0
  - 1.0
  - 1.0
  - 1.0
  - 5.0
  - 5.0
  - 1.0
  - 1.0
  min:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
parameters_forward:
- 0.33997739825657797
- 0.04308717815947438
- 0.05648210855111
- 0.3997172081557205
- 1.0016450124535874
- 0.6469007728703678
- 0.4983831221732382
- 0.10603527733882195
paths:
  input_data: examples/forward_prediction_intervals/future_data.csv
  output_dir: examples/forward_prediction_intervals
prc: 1.0
project_name: projection
run_mode: FORWARD
series: future
station_name: Alpha
time_resolution: 1d
version: 8
