project_name: "optimizer_comparison"
station_name: "DAV"
series: "c"
time_resolution: "1d"
version: 8
Tice_cover: 0.0
objective_function: "NSE"
integrator: "RK4"
run_mode: "PSO"
prc: 1.0

paths:
  input_data: "examples/validation/Switzerland/DAV_2327_cc.csv"
  output_dir: "examples/optimizer_comparison"

optimization:
  n_runs: 40
  mineff_index: -999.0
  n_particles: 10
  c1: 2.0
  c2: 2.0
  wmax: 0.9
  wmin: 0.4
  mcmc_walkers: 32
  mcmc_steps: 2000

parameter_bounds:
  min: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  max: [10.0, 1.0, 1.0, 1.0, 1.0, 10.0, 1.0, 1.0]
